### PR TITLE
RTI 12237 upgrade elixir

### PR DESCRIPTION
**Pull request by maco**
Update to using Elixir 1.12 and the latest version of flow (which uses updated gen_stage).

### CODE REVIEW

**Review by elbrujohalcon — APPROVED** [review]

**Review by qhool — APPROVED** [review]

**Review by pbrudnick — COMMENTED** [review]
I think that's not required anymore:
https://github.com/AdRoll/exmld/blob/e0187d114227cb28d1eb3ac94e29c099dfe5c221/mix.exs#L27

**Comment by pbrudnick** [comment]
Actually, I think this library does not use `Flow` anymore, instead uses `GenStage`

**Comment by maco** [comment]
(for anyone looking at this futurely: it's used in exmld.ex ; code search betrayal!)

**Comment by pbrudnick** [comment]
> Actually, I think this library does not use `Flow` anymore, instead uses `GenStage`

Sorry, forget about it
My quick search was only showing the top 2 appearances..
Captura de Pantalla 2022-06-02 a la(s) 13 08 39

**Pull request merged**
